 Arthematic Operators 

a=int(input("Enter a"))
b=int(input("Enter b"))
print("Arthematic Operations in int")
print("Addition :",a+b)
print("Subtraction :",a-b)
print("Multiplication :", a*b)
print("Division :",a/b)
print("Remainder :",a%b)
print("Floor Division :",a//b)
print("value of Expotent :",a**b)

a=float(input("Enter a"))
b=float(input("Enter b"))
print("Arthematic Operations in float")
print("Addition :",a+b)
print("Subtraction :",a-b)
print("Multiplication :", a*b)
print("Division :",a/b)
print("Remainder :",a%b)
print("Floor Division :",a//b)
print("value of Expotent :",a**b)


a=int(input("Enter a"))
b=int(input("Enter b"))
c=complex(a,b)
print(c)
a=int(input("Enter a"))
b=int(input("Enter b"))
d=complex(a,b)
print(d)
print("Arthematic Operations in complex")
print("Addition :",c+d)
print("Subtraction :",c-d)
print("Multiplication :", c*d)
print("Division :",c/d)
print("Remainder :",c%d)
print("Floor Division :",c//d)
print("Exponent :",c**2)
